src/lib.rs
All the DWARF sections are within the `__DWARF` segment, but the `__eh_frame` section is inside the `__TEXT` section since it is needed at runtime for exception handling.
=> Fix getting the `__eh_frame` section from Mach-O files

Cargo.toml, examples/nm.rs, src/lib.rs
There's sure to be lots missing from this, but it's enough to match most of the nm and llvm-nm output for some ELF and Mach-O files, and should be sufficient for addr2line (but I haven't done that yet).
Fixes #15
=> Add symbols API

examples/objdump.rs, src/lib.rs
This adds SectionIterator which has an enum inside which lets
us store more data than using a trait object would. Unfortunatelly,
this solutions ends up a little verbose, but we get nice type safety
out of it. Fixes #16
=> Add an API for iterating over the sections in a file

Cargo.toml, src/elf.rs, src/lib.rs, src/macho.rs, src/pe.rs, src/traits.rs
I have another PR forthcoming to start the `moria` crate, so I've added some useful methods to `Object` in support of that. `Object::has_debug_symbols` is pretty straightforward, and `Object::debug_file_info` exposes the platform-specific info necessary to locate debug info stored in a separate file.
=> Add some methods useful for locating debug symbols

Cargo.toml, src/elf.rs, src/lib.rs, src/macho.rs, src/pe.rs, src/traits.rs
I created two separate features for this, `compression` and `zdebug`. I made `zdebug` separate because in theory someone could extend `flate2` to build without `std`, and then `compression` would build without `std` but `zdebug` would not because it requires `format!` (and I don't know how to do string concatenation without `std`). Perhaps we should just not worry about that and eliminate `zdebug`, though the extra feature is on by default so it's not much of a burden.
Note that this is a breaking change to the `find_section_data_by_name`, but I think that's what Philip wanted.
=> Automatically decompress compressed ELF and .zdebug sections

src/lib.rs
Fixes #53 
I looked into also adding feature flags, but didn't for two reasons
- we would still have to enable all goblin features anyway for `peek_bytes`
- the cfg attributes were getting messy, eg due to unused lifetimes on enums (maybe it would have been better to leave the lifetimes on wasm after all, but that wasn't the only case)
=> Define NativeFile

examples/objdump.rs, src/elf.rs, src/lib.rs, src/macho.rs, src/pe.rs, src/traits.rs, src/wasm.rs
I'm not sure that putting both build-id and gnu_debuglink in the same enum is correct, since files can have both. Need to split into separate functions? Any opinion on this @luser?
=> Implement debug_file_info() for ELF

Cargo.toml
Probably should come up with a way of testing this properly so it doesn't break again. Currently I'm partially testing by linking with a binary that uses `#[no_std]`, but even that's not correct because I'm still getting linker errors about missing `_Unwind_Resume`. @whitequark Since you've done a bit of no_std work, can you give any pointers on how to test this properly?
=> Fix scroll features for no_std builds

Cargo.toml
Needed for the no_std work in addr2line. Not much has changed, but uuid is part of the public API so it's a breaking change.
=> Bump version to 0.9.0

src/pe.rs
These changes were sufficient to allow reading DWARF records on Mac, Linux, and Windows systems in my application.  I found no formal documentation on how to read DWARF records from a PE file, but arrived at this solution by looking at other code and poking around in a PE file.
DWARF sections names in PE files are stored indirectly through a symbol table.
Names of the form "/n" where "n" is a number indicate the section name is
stored in index "n" of a hidden symbol table.  The hidden symbol table immediately
follows the COFF symbol table and is a sequence of null terminated CStrings.
=> Issue #40 -- Support DWARF-in-PE

examples/objdump.rs, src/elf.rs, src/lib.rs, src/macho.rs, src/pe.rs, src/traits.rs, src/wasm.rs
This returns the relocations only. It is up to the caller to apply them.
These are the minimum ELF relocations that I need to dwarfdump an object file. The Mach-O relocations weren't needed for that (because it has implicit addends), but it helps generalize the API.
I didn't look into PE relocations (it'll only be dynamic linking relocations?), and we don't support COFF yet.
WASM is probably going to be rather different, but I didn't look into it much. It'll be okay to add WASM specific entries to `RelocationKind`.
Note: there's an initial commit with rustfmt changes.
Fixes #4
=> Implement some ELF/Mach-O relocations

src/elf.rs, src/lib.rs, src/macho.rs, src/pe.rs, src/traits.rs, src/wasm.rs
This is needed to make use of the symbol value in relocations.
=> Add File::symbol_by_index

src/elf.rs
From Travis log:
```rust
$ if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo build --no-default-features; fi
Compiling object v0.11.0 (/home/travis/build/gimli-rs/object)
warning: unused variable: `section_name`
--> src/elf.rs:138:9
|
138 |         section_name: &str,
|         ^^^^^^^^^^^^ help: consider prefixing with an underscore: `_section_name`
|
= note: #[warn(unused_variables)] on by default
Finished dev [unoptimized + debuginfo] target(s) in 0.57s
```
=> Fix unused variable `section_name` of `elf::zdebug_section_by_name`

examples/nm.rs, examples/objdump.rs, src/elf.rs, src/lib.rs, src/macho.rs, src/pe.rs, src/traits.rs, src/wasm.rs
The `SectionKind` variants may be too ELF specific. I expect them to evolve as Mach-O and PE support is improved.
~~Needs a new goblin release first.~~ (Deleted that commit for now.)
=> Add more details for sections and symbols

Cargo.toml
Mainly so that an addr2line release can use it.
=> Bump version to 0.12.0

src/macho.rs
For example `.rustc` used to be replaced with `__rustc` before searching, which meant `.rustc` was not findable
cc https://github.com/bjorn3/rustc_codegen_cranelift/pull/435
=> [mach] Make section_by_name support loading sections starting with dot

src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs
This is mainly x86-64 relocations for Mach-O and COFF.
Relocations now have both a kind and subkind. The subkind is used for architecture specific variations.
Relocations now have a `RelocationTarget`, since Mach-O relocations can specify either a symbol or a section. This won't matter in the write module, because there we can model it as section symbols that aren't written.
@pchickey Not sure how much you know about relocations. While this PR is still only for the read module, my main concern here is whether the `RelocationKind` + `RelocationSubkind` abstraction is suitable for users of the write module.
The intent is that these kinds are independent of file format. Additionally, `RelocationKind` is intended to be mostly independent of architecture, with `RelocationSubkind` containing …
=> Add more relocations

src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/pe.rs
@pchickey I did this a bit different from the scope/visibility support you added in faerie, because I think this fits Mach-O better. I didn't see where you used the faerie support in lucet, so I'm interested if this still meets the needs you had from faerie.
=> Add symbol scope

.travis.yml, Cargo.toml, examples/objcopy.rs, src/common.rs, src/lib.rs, src/read/macho.rs, src/read/mod.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, src/write/string.rs, src/write/util.rs, tests/round_trip.rs
In addition to the minimal smoke tests added in this PR, I have manually tested using the `objcopy` example on some sample ELF/COFF/Mach-O object files.
Also tested with the following WIP branches:
https://github.com/philipc/cranelift/tree/object
https://github.com/philipc/lucet/tree/object (ELF)
https://github.com/philipc/rustc_codegen_cranelift/tree/object (ELF and COFF)
Those branches still need various rework, but I don't think any of that will affect the API added in this PR.
@pchickey If you want to test lucet with Mach-O too then that would be great.
@sunfishcode If you have time to look at this, that would be appreciated. I've addressed some of the things you noted in https://github.com/CraneStation/cranelift/issues/761, but there's probably more (and I haven't implemented `Write` …
=> Add write support

Cargo.toml, src/read/elf.rs, src/read/macho.rs, src/write/elf.rs, src/write/macho.rs
This updates object to target-lexicon 0.8, which corresponds to the version now being used in cranelift, which is needed for https://github.com/CraneStation/cranelift/pull/937.
I'm also open to suggestions about how target-lexicon could make what this code is doing tidier. Would it be more clear if we renamed `ArmArchitecture::Arm` to `ArmArchitecture::Generic`?
=> Update to target-lexicon 0.8.

src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, tests/tls.rs
Fixes #138 
cc @bjorn3 
Compile tested only.
I also considered adding TLS variants to `RelocationKind`, but decided there was too little in common between the architectures, and the code generation already needs to know about the differences anyway.
=> write: add TLS sections

src/read/any.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/pe.rs, src/read/traits.rs, src/read/wasm.rs
Add a method for segments which returns the on-disk file offset and
segment size (distinct from the in-memory size, for formats where they
can differ).
This is similar to `data()`, but rather than returning a slice of the
data itself, it returns the location of the data.  This is useful for
when we want to locate the segment within a memory mapping, or use it
to generate the parameters for an IO syscall.
The `Segment::` and `Section::` methods are very similar, except that sections
can have no content associated with them. To handle this, Segment::offset returns
`Option<(u64, u64)>` where None indicates no loadable content.
(Open to suggestions on name.)
=> Add ObjectSegment::offset and ObjectSection::offset methods

src/common.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs
Fixes #141 
cc @bjorn3 
The differences from #142 are:
- read/write round trip should work
- avoid any knowledge of specific custom relocation values
In particular, this means that cranelift may need to handle the addend differently.
=> write: support custom Mach-O relocations

examples/nm.rs, examples/objcopy.rs, src/common.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/pe.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, tests/common.rs, tests/round_trip.rs, tests/tls.rs
Also hopefully fixes address calculations for BSS sections in Mach-O.
~~`write::Object` will probably also need an `add_common_symbol` method so code generators can handle the differences between ELF and Mach-O (and COFF, which I have no idea about yet), but that's not needed for objcopy, so leaving that until someone needs/tests it.~~ Done.
Closes #149, closes #158 
cc @jayvdb
=> Implement common and absolute symbols for ELF and Mach-O

examples/objcopy.rs, src/common.rs, src/read/any.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/pe.rs, src/read/traits.rs, src/read/wasm.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, tests/bss.rs, tests/common.rs, tests/round_trip.rs, tests/tls.rs
Also a couple of COFF write fixes.
Fixes #159, fixes #160 
WIP: there's probably more non-COFF flags that still need to be copied, but probably worth testing if it really does fix #159, cc @jayvdb
=> objcopy: copy file, section, and symbol flags

Cargo.toml, src/elf.rs, src/endian.rs, src/lib.rs, src/read/any.rs, src/read/elf.rs, src/read/mod.rs, src/read/util.rs, src/write/elf.rs, tests/round_trip/elf.rs
For ELF read/write, uses `bytemuck` instead of `scroll`, and reimplements the goblin ELF support, as discussed in #167 . `bytemuck` was chosen over `zerocopy` because `zerocopy`'s `AsBytes` derive doesn't work for generics, and it doesn't allow manual impls.
Also fixes some bugs: fixes #168 , fixes #169 , fixes #170  
@fitzgen I don't know if you are interested in reviewing this... it's quite large.
`src/elf.rs` is almost completely based on `elf.h`, and probably isn't reviewing in detail.
`src/endian.rs` is based on gimli's `endianity.rs`, with the differences being that it doesn't use `byteorder`, and it supports aligned integers instead of unaligned integers. This is probably a candidate for a common crate that covers both.
=> Convert ELF read/write to use bytemuck

src/lib.rs, src/macho.rs, src/read/any.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/util.rs, src/write/macho.rs, tests/round_trip/common.rs, tests/round_trip/tls.rs
For Mach-O read/write, use bytemuck instead of scroll, and reimplement the goblin Mach-O support, as discussed in #167 .
Also fix some bugs: fixes #174, fixes #175
=> Convert Mach-O read/write to use bytemuck 

examples/nm.rs, examples/objcopy.rs, src/read/coff.rs, src/read/elf.rs, src/read/mod.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, tests/round_trip/mod.rs
For ELF, file symbols were being emitted with `STB_GLOBAL` instead
of `STB_LOCAL`. This was because their section was set to `Undefined`,
which overrode the symbol scope.
Fix by using a new `SymbolSection::None` in `add_file_symbol`.
This also changes the section to `None` when reading, which makes our
round trips consistent.
Fixes #179
=> Use SymbolSection::None for file symbols

Cargo.toml, src/elf.rs, src/endian.rs, src/lib.rs, src/macho.rs, src/pe.rs, src/pod.rs, src/read/any.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/pe.rs, src/read/util.rs, src/read/wasm.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs
Add a `Pod` trait to replace bytemuck usage. This is relatively simple, and lets us provide a more convenient API than bytemuck.
For PE and COFF read/write, use `Pod` instead of scroll, and reimplement the goblin PE/COFF support, as discussed in #167 . This is notably missing export/import parsing, but I don't think anything used them currently, and I plan to rework it as part of #182.
Fixes #178, fixes #183
=> Convert PE/COFF to use Pod

Cargo.toml, examples/objdump.rs, src/read/any.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/pe.rs, src/read/traits.rs, src/read/wasm.rs
This means we don't need to force `ObjectSection::data` to return `Cow` for all file formats. This makes it clear that no allocation occurs, even if it previously didn't.
Also implements returning the "name" section as symbols.
I investigated using `wasmparser`, but its API didn't really seem better for this either. At least the parsing we need can be done with little code.
=> read/wasm: avoid copying data

src/read/mod.rs
I want to return a symbol without having to borrow the cached list of symbols for a object file.
=> Derive Clone for Symbol

src/pod.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/pe.rs, src/read/util.rs, src/read/wasm.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, src/write/util.rs
These make it more convenient to read/write `Pod` types, and harder to cause indexing panics when reading.
Fixes #32 
Absence of indexing panics checked using [findpanics](https://github.com/philipc/findpanics/).
@fitzgen `src/pod.rs` is probably the most in need of review (including the unsafe code).
=> Add Bytes and BytesMut helpers

examples/objcopy.rs, src/read/any.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/pe.rs, src/read/traits.rs, src/read/wasm.rs
The behaviour of methods should not depend on a cargo feature.
So we give `ObjectSection::uncompressed_data` fixed behaviour,
but make its presence depend on the feature.
This requires making the traits sealed, which we probably should
do anyway.
Also make it possible to handle decompression errors.
If the user wants to ignore errors then they should do that
themselves.
=> Fix compression feature

Cargo.toml, src/read/wasm.rs
This switches reader from manual implementation to wasmparser in order to prepare for implementation of new features and better integration like #196.
For the simplicity of review, this changeset intentionally doesn't implement any new features yet nor changes public API, and instead preserves same functionality but with wasmparser instead of a manual reader.
=> Switch to wasmparser

src/pod.rs, src/read/any.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/pe.rs, src/read/util.rs
Also use `Result` more in internal APIs. No change to external API yet.
=> read: change `Bytes` methods to return `Result`

Cargo.toml, examples/objcopy.rs, examples/objdump.rs, src/lib.rs, src/read/any.rs, src/read/coff.rs, src/read/elf.rs, src/read/macho.rs, src/read/mod.rs, src/read/pe.rs, src/read/traits.rs, src/read/wasm.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, tests/round_trip/bss.rs, tests/round_trip/common.rs, tests/round_trip/mod.rs, tests/round_trip/tls.rs
Add new-types for errors, and return errors from trait methods where appropriate.
Still need better error handling for `read::Symbol` methods, but that can be done when it is converted to a trait too.
Fixes #194 
@fitzgen review as much as you feel like :)
=> Improve error handling

src/write/elf.rs
This is the fix for the problems I had at https://bytecodealliance.zulipchat.com/#narrow/stream/225524-cranelift-new-backend/topic/cg_clif-integration/near/194042579
=> write/elf: fix elf_has_relocation_addend for Aarch64

src/lib.rs, src/pod.rs, src/read/coff/file.rs, src/read/coff/section.rs, src/read/coff/symbol.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/read/elf/section.rs, src/read/elf/symbol.rs, src/read/macho/file.rs, src/read/macho/load_command.rs, src/read/macho/symbol.rs, src/read/mod.rs, src/read/pe/file.rs, src/read/pe/mod.rs, src/read/pe/section.rs, src/read/util.rs, src/write/elf.rs
For some applications it is desirable to only parse the minimum needed, but currently the unified API has to parse everything that is required to implement the unified traits. This PR starts exposing the lower level parsing API. This API is necessarily specific to each file format. It is aimed at allowing access to symbols for use in backtraces.
Very little of this PR is new functionality, but notable changes are:
- elf: fix SHT_SYMTAB_SHNDX handling for dynamic symbols
- pe: fix section indices to be 1-based
Covers most of #215 (cc @alexcrichton)
=> read: start exposing lower level parsing API

Cargo.toml, src/read/wasm.rs
Add support for:
- Symbols for imports (with Dynamic scope).
- "Virtual" file symbols to delimit imports from main file.
- Symbols for local functions (with Compilation scope and real address and size).
- Symbols for exports.
- Text (functions) and Data (everything else) symbol kinds.
- Start section converted to an entry address.
- Symbols for local functions.
- Predefined section kinds based on the section code.
Note that if a function is exported, then it will appear under its exported names with a Dynamic scope. Otherwise it's a local function and will appear with its debug name from the "names" section and a Compilation scope.
Also note that this adds support for fully built Wasm modules, but not for dynamic linking yet. That one will require adding more code for parsing relocation …
=> Enhance Wasm symbol reading

src/elf.rs, src/pod.rs, src/read/any.rs, src/read/coff/section.rs, src/read/elf/section.rs, src/read/macho/section.rs, src/read/mod.rs, src/read/pe/section.rs, src/read/traits.rs, src/read/wasm.rs, tests/round_trip/elf.rs
Changed `Object::uncompressed_data` to always be present, but return an error
if the data is compressed and the `compression` feature is disabled.
Added `Object::compressed_data` to return information about the compression
method, allowing users to implement their own decompression.
Also fix decompression of unaligned GNU ZLIB sections.
=> read: improve compression APIs

.travis.yml, Cargo.toml
This applies the same change as gimli-rs/gimli#503 to this crate.
(also see https://github.com/rust-lang/backtrace-rs/issues/328 for some context)
=> Prepare for inclusion into libstd

Cargo.toml, src/endian.rs
While the structs defined in this crate have the alignment required by the specifications, some toolchains violate these requirements. Add an `unaligned` feature that allows these files to be processed, at the cost of potentially slower code.
Fixes #230 
I've kept this out of the `all` feature for now. I'm not sure if this should be enabled by default. @alexcrichton What are your thoughts on what `backtrace-rs` will want for this? I'm not sure how much the performance of this matters, and whether you want to selectively enable it for some architectures (most likely x86-64).
=> Add `unaligned` feature

Cargo.toml, src/lib.rs
=> Print error when --all-features is used

src/elf.rs
Compressed sections are commonly emitted with the wrong alignment. This has been fixed in more recent versions of the major compilers, but for now let's support the invalid alignment even with the
unaligned feature disabled, since performance here doesn't matter much.
Fixes #235
=> elf: allow unaligned compression headers

src/pod.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, src/write/util.rs
Fixes #240 
This PR implements proposed below trait.
> Writing via a trait would be fine. I think pre-allocation should be a fallible method of that trait so that we don't complicate the size calculations. So it would need methods for:
> * allocate
> * write
> * len (for debug asserts)
=> Use WritableBuffer to emit object file

src/common.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/write/elf.rs
This adds basic support for the s390x architecture and its most common relocation types.
This is a prerequisite for adding s390x support to wasmtime.
=> Add support for s390x

src/write/elf.rs
This is necessary to support weak linkage on statics in cg_clif.
=> write/elf: Check symbol.weak before symbol.is_undefined()

examples/nm.rs, examples/objcopy.rs, examples/objdump.rs, src/read/any.rs, src/read/coff/comdat.rs, src/read/coff/file.rs, src/read/coff/section.rs, src/read/coff/symbol.rs, src/read/elf/file.rs, src/read/elf/symbol.rs, src/read/macho/file.rs, src/read/macho/symbol.rs, src/read/mod.rs, src/read/pe/file.rs, src/read/pe/section.rs, src/read/traits.rs, src/read/wasm.rs, tests/round_trip/bss.rs, tests/round_trip/comdat.rs, tests/round_trip/common.rs, tests/round_trip/elf.rs, tests/round_trip/mod.rs, tests/round_trip/tls.rs
This allows users to only store the parts of the symbol that they
are interested in. For example, the user may want to only store
the symbol index and retrieve specific details from the symbol table
only as needed.
`Object::symbol_map` now returns a map containing only symbol names and
addresses, which is the most common use case. `SymbolMap` can be
constructed with custom symbol entries if other information is required.
This method also uses the dynamic symbol table if there are no
debugging symbols.
Also fixes COFF/PE symbols to give the correct address. Previously
they weren't including the image base address and the section address.
=> Replace `Symbol` with a trait

examples/objdump.rs, src/macho.rs, src/pe.rs, src/pod.rs, src/read/any.rs, src/read/coff/file.rs, src/read/elf/file.rs, src/read/elf/symbol.rs, src/read/macho/file.rs, src/read/macho/load_command.rs, src/read/macho/symbol.rs, src/read/mod.rs, src/read/pe/file.rs, src/read/pe/section.rs, src/read/traits.rs, src/read/wasm.rs
Support is as follows:
- ELF: `.dynsym` entries. If required, we could extend this to parse GNU symbol versioning as well.
- Mach-O: `LC_DYSYMTAB` entries, with support for library names if `MH_TWOLEVEL` is used.
- PE: entries from the import data directory and export data directory
- COFF: not implemented. Probably not useful since this isn't an executable.
- Wasm: not implemented until someone requests it.
Fixes #182
=> read: implement imports and exports

examples/readobj.rs, src/elf.rs, src/read/coff/relocation.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/read/mod.rs
I'm currently using a vendored version of object that adds support for more relocations. Since this crate does not expose any of the raw elf data structures and only exposes a fraction of the information, vendoring is usually necessary to use this crate for platforms not fully supported by it. In particular, the Relocation object throws away information present in the underlying data.
In my version I've made incompatible changes to the public interface to support mips64el relocations. Please feel free to add these changes to the crate (possibly in a backwards compatible way) so that I can stop vendoring it. Alternatively you could expose the internal data structures which would also make vendoring unnecessary.
=> Add support for more relocations

src/read/pe/file.rs
The fields `dos_header` and `nt_headers` of a `PeFile` are private (or rather, they are defined `pub(crate)`).
They may be of interest for a user who has already parsed a file into a `PeFile`, so I have added getters for them.
I am not sure whether this would have made sense as well to add a getter for the `CoffCommon` part and to turn `PeFile::data_directory` and `PeFile::data_at` public, so I did not change them.
Changing the fields form `pub(crate)` to `pub` (instead of implementing getters) would have made the trick as well, but I'm not experienced enough with `object` to tell whether that would be a good idea.
=> Added getters for PeFile

src/read/macho/file.rs, src/read/traits.rs
Fixes https://github.com/gimli-rs/gimli/issues/547
=> read/macho: truncate system section names longer than 16 bytes

src/read/read_ref.rs, tests/round_trip/bss.rs, tests/round_trip/comdat.rs, tests/round_trip/common.rs, tests/round_trip/elf.rs, tests/round_trip/mod.rs, tests/round_trip/tls.rs
While it has a slight convenience, this may result in code bloat.
=> read: delete impl ReadRef for Vec

Cargo.toml
This avoids a dependency that is out of date and which most users do not need.
=> Disable wasm feature by default

src/pod.rs
=> pod: add from_bytes_mut and slice_from_bytes_mut

src/pod.rs
=> pod: add bytes_of_mut and bytes_of_slice_mut

examples/objdump.rs, src/read/any.rs, src/read/mod.rs, src/read/pe/file.rs, src/read/traits.rs
Just like we can get the UUID from macho files and the build-id from ELF
files, this change allows users to pull out the PDB info (path, age, and
GUID) from PE files.
macho and ELF files will return `Ok(None)`
=> Add ability to parse pdb info from PE file

examples/readobj.rs, src/read/macho/file.rs, tests/round_trip/macho.rs
This allows parsing Mach-O images inside dyld shared cache files (#268):
The dyld shared cache contains multiple images at different offsets; all these
images share the same address space for absolute offsets such as symoff. Due to
these absolute offsets, one cannot just parse the images by subsetting the input
slice and parsing at header offset zero.
This patch is a breaking change because it adds a header_offset argument to the
MachHeader methods load_commands and uuid, and MachHeader is part of the public API.
=> Add MachOFile::parse_at_offset

src/common.rs, src/elf.rs, src/write/elf.rs
Added for rust-lang/rust#84449
=> Add basic support for mips64/powerpc/powerpc64/riscv64

examples/objdump.rs, src/read/any.rs, src/read/coff/file.rs, src/read/elf/file.rs, src/read/macho/file.rs, src/read/mod.rs, src/read/pe/file.rs, src/read/pe/section.rs, src/read/traits.rs, src/read/wasm.rs
=> read: add Object::relative_address_base

src/elf.rs, src/write/elf.rs, tests/round_trip/mod.rs
=> Relocation writing fixes

src/common.rs, src/read/elf/relocation.rs, src/write/elf.rs
Necessary for AArch64 support in cranelift-object.
=> Add native support for writing ELF R_AARCH64_CALL26 relocations

src/read/pe/file.rs
Having those exposed allows the user to explore the full internals of a `PeFile`, while simultaneously using the higher-level convenience functions exposed by the `Object` trait.
All the types (the `SectionTable` and pe `ImageDataDirectory`) are already public, so the increase in API surface is fairly minimal.
I'm personally using this to parse the Import table myself, in order to better handle certain edge scenarios (such as being able to tell the difference between a missing import directory from an empty directory).
=> Expose PeFile data, section_table and data_directory

examples/readobj.rs, src/read/any.rs, src/read/coff/file.rs, src/read/coff/section.rs, src/read/coff/symbol.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/read/elf/section.rs, src/read/elf/symbol.rs, src/read/macho/dyld_cache.rs, src/read/macho/file.rs, src/read/macho/load_command.rs, src/read/macho/symbol.rs, src/read/pe/file.rs, src/read/pe/section.rs, src/read/read_cache.rs, src/read/read_ref.rs, src/read/util.rs
Before this PR, StringTables are read in their entirety and do not make use of the partial read ability of `ReadRef`. This is fine in most cases, but it is problematic for the dyld shared cache.
The dyld shared cache has a shared string table which is about 340MB big. Only a fraction of those strings are needed by each embedded library. For example, if I dump all AppKit symbols with their names from the dyld shared cache on macOS 11.3, this patch reduces the number of bytes read from 347.4 MB to 4.8 MB.
This patch makes use of the relatively new `read_bytes_at_until` method. But it also extends it by one parameter, `upper_bound`, so that the string table's size can be honored.
We currently have a hardcoded limit of 4096 bytes for the string length in the ReadCache. It's possible that this …
=> Support partial reading of string tables

examples/readobj.rs, src/elf.rs, src/read/elf/hash.rs, src/read/elf/mod.rs, src/read/elf/section.rs, src/read/elf/symbol.rs, src/read/elf/version.rs, src/read/mod.rs
Symbol version support is good enough for the readobj example to dump the raw values, but it will need some higher level support later.
=> read/elf: symbol hash and version support

src/pe.rs
Add RISC-V constants for COFF headers and base relocation types
=> pe: Add RISC-V constants for COFF headers and base relocations

src/pod.rs, src/write/coff.rs, src/write/elf.rs, src/write/macho.rs, src/write/mod.rs, src/write/util.rs
- implement `WritableBuffer` for `Vec`
- rename `WritableBuffer::extend` to `write_bytes` to avoid conflict with `Extend::extend`
- add methods for writing `Pod` types
- replace `BytesMut` with a trait
- move `WritableBuffer` and `BytesMut` to `write::util`
=> `WritableBuffer` improvements

src/read/pe/file.rs
Closes #340 
In case that's an acceptable solution.
This can correctly parse the imports of simple.exe (see the issue), but I'm not sure it does not break things elsewhere yet (it looks OK on my use cases, but I haven't tested it extensively yet)
=> PE: import directory can have null size (but not a null pointer)

examples/readobj.rs, src/read/elf/dynamic.rs, src/read/elf/section.rs
Previously we only supported segments.
Also add helpers for determining the value type of dynamic entries.
=> read/elf: add support for .dynamic sections

src/read/coff/section.rs, src/read/pe/file.rs
This change adds supports for overlay detection in `object`.
A data overlay is defined as the part of a PE file that is not declared in its headers, i.e. the part of the file past all declared sections.
That's a place where e.g. authenticode certificates are embedded (and where some binaries may also use to conceal data)
=> PE: add overlay detection

src/read/mod.rs, src/read/pe/export.rs, src/read/pe/file.rs, src/read/pe/mod.rs, src/read/pe/pe_export.rs, src/read/traits.rs
This MR adds supports for PE exports by ordinal.
Also, this adds the "forwarded export", which is another PE-specific concept
=> PE exports by ordinal

examples/objcopy.rs, examples/objdump.rs, src/read/any.rs, src/read/coff/file.rs, src/read/elf/file.rs, src/read/macho/file.rs, src/read/mod.rs, src/read/pe/file.rs, src/read/traits.rs, src/read/wasm.rs
Use this to check for supported object kind in `objcopy` example.
=> read: add `Object::kind`

src/read/pe/section.rs
Usually, sections are padded, but when they're not, a bug prevented accesses to the first byte of some sections
=> Fixed reading PE section data for contiguous sections

examples/readobj.rs, src/read/mod.rs, src/read/pe/export.rs, src/read/pe/file.rs, src/read/traits.rs
Also:
- fix parsing of export tables that have no names
- add parsing of strings for forwarded exports
- add more support in readobj example
- some arbitrary style changes
cc @daladim
=> read/pe: add ExportTable

src/read/coff/section.rs
Because newlines break the Markdown URL syntax
=> Fixed a URL in a doc comment

Cargo.toml
This accompanies BurntSushi/memchr#89 to help resolve
rust-lang/backtrace-rs#432
Note that this can't actually land until https://github.com/BurntSushi/memchr/pull/89 is published
=> Activate memchr's dep-of-std feature

src/write/elf/writer.rs
As per dicussion at https://github.com/gimli-rs/object/pull/325#issuecomment-902268805, allows for creating an dynamic symbol table with just the null entry.
=> write/elf: add method to reserve null dynamic symbol table entry

src/read/pe/export.rs
It's common for the export table to have 0 for each virtual address, and number of names set to 64.
=> read/pe: fix parsing of empty export tables

src/write/mod.rs
This commit adds `Section::{data, data_mut}` accessors to
`write::Section` to allow accessing data after it's been appended. The
motivation for this is that in Wasmtime we build an `Object` but we try
to patch relocations after the locations of all symbols are known,
handling them before load-time. Currently the logic of
appending-with-alignment is duplicated in Wasmtime but allowing access
to the underlying section data as-been-appended-so-far should enable us
to remove that duplication.
=> Allow access to section contents while building

src/write/coff.rs, src/write/elf/object.rs, src/write/elf/writer.rs, src/write/mod.rs, src/write/util.rs
=> Add `write::Object::write_stream`

crates/examples/src/bin/objcopy.rs, src/write/coff.rs, src/write/elf/object.rs, src/write/macho.rs, src/write/mod.rs
@bjorn3 Will this fix https://github.com/gimli-rs/object/pull/348#issuecomment-894684012? You'll need to use `set_section_data` instead of `append_section_data`. The cost is that other users may need to specify `'static` for the lifetime. Maybe it's worth using `Cow` for the section and symbol names too.
=> write: use Cow for Section::data

Cargo.toml
In src/write/string.rs, `StringTable` uses `IndexSet` with one generic
parameter. `IndexSet` only supports being passed one generic parameter
[when `indexmap`'s `std` feature is enabled]. `indexmap`
[attempts to autodetect] whether `std` is supported, but it doesn't
always succeed. This patch explicitly enables `indexmap/std` when
`object`'s own `std` feature is enabled, to avoid the autodetection
path.
[when `indexmap`'s `std` feature is enabled]: https://github.com/bluss/indexmap/blob/master/src/set.rs#L62
[attempts to autodetect]: https://github.com/bluss/indexmap/blob/master/build.rs#L3
=> Make `std` imply `indexmap/std`.

src/write/pe.rs
=> write::pe::Writer: Add write_file_align function.

src/read/coff/section.rs, tests/coff.rs, tests/integration.rs
=> read/coff: Add support for extended relocations.

Cargo.toml, crates/examples/Cargo.toml, src/lib.rs, src/write/coff.rs, src/write/elf/object.rs, src/write/elf/writer.rs, src/write/macho.rs, src/write/mod.rs, src/write/pe.rs, src/write/string.rs, src/write/util.rs
This PR relaxes the requirement that `write_core` and `write` need and must enable the `std` feature.
To enable the ability to use this crate's awesome write functionality in no_std environments.
For example, this is needed when using various `wasmtime` subcrates in a no_std environment.
* I have tested this with all combinations of features that I could come up with. The cargo tests also pass.
* The `write` feature could optionally enable `std`, if desired. Currently I didn't leave that feature there, but in the past, the `write_core` feature itself also enabled the `std` feature. I'm happy to make this change if requested.
* The few write-related functions that require `std` have now been gated with a `#[cfg(feature = "std")]` attribute. Currently this only includes `StreamingBuffer`, …
=> Make the `write_core` (and optionally `write`) features `no_std` compatible

crates/examples/src/bin/dyldcachedump.rs, crates/examples/src/bin/objdump.rs, crates/examples/src/objdump.rs, crates/examples/tests/testfiles.rs, src/macho.rs, src/read/any.rs, src/read/macho/dyld_cache.rs, src/read/macho/file.rs, src/read/macho/section.rs, src/read/macho/segment.rs
Fixes #358.
This adds support for the dyld cache format that is used on macOS 12 and
iOS 15. The cache is split over multiple files, with a "root" cache
and one or more subcaches, for example:
```
/System/Library/dyld/dyld_shared_cache_x86_64
/System/Library/dyld/dyld_shared_cache_x86_64.1
/System/Library/dyld/dyld_shared_cache_x86_64.2
/System/Library/dyld/dyld_shared_cache_x86_64.3
```
Additionally, on iOS, there is a separate .symbols subcache, which
contains local symbols.
Each file has a set of mappings. For each image in the cache, the
segments of that image can be distributed over multiple files: For
example, on macOS 12.0.1, the image for libsystem_malloc.dylib for the
arm64e architecture has its __TEXT segment in the root cache and the
__LINKEDIT segment in the .1 subcache - …
=> Add support for split dyld shared cache.

src/write/elf/object.rs, src/write/elf/writer.rs
Use this to ensure `Object` creates the null symbol when no symbols are defined.
=> write/elf: add `Writer::reserve_null_symbol_index`

src/read/wasm.rs
This a work-around for (#403). 
The version of `wasmparser` currently in use does not support   [extended name sections](https://github.com/WebAssembly/extended-name-section/blob/main/proposals/extended-name-section/Overview.md) will return an error when such an unknown subsection is encountered.
This commit is a quick work-around until `wasmparser` is updated to the most recent version. This is a rather big undertaking unfortunately; it requires major changes in `wasm.rs` since the API of `wasmparser` has changed quite a bit.
If I find the time, I will attempt that and create another PR.
One downside of this work-around is that ill-formed name subsections (e.g. for function names) are silently ignored, but I think this is a manageable tradeoff until `wasmparser` is updated. In case you …
=> Quickfix: Ignore errors when loading name subsection. (#403)

src/read/coff/symbol.rs, src/read/pe/file.rs
Some binaries (not sure what toolchain has generated them) may have pointers to COFF symbols that point to nothing.
Since COFF symbols tables are deprecated anyway, it could be better to ignore these symbols than returning an `Err` that will prevent the whole PE file from parsing.
I know you're not always happy to remove error conditions for the sake of parsing more binaries, so I'd like to have your opinion on such a "fix" :-)
Example of such binaries: git for Windows (at least some builds).
* Download [PortableGit-2.29.2.3-64-bit.7z.exe](https://github.com/git-for-windows/git/releases/download/v2.29.2.windows.3/PortableGit-2.29.2.3-64-bit.7z.exe) from [their release page](https://github.com/git-for-windows/git/releases/tag/v2.29.2.windows.3)
* Run it so that it extracts itself
* The …
=> Accept populated COFF symbol headers

src/write/coff.rs, tests/round_trip/comdat.rs, tests/round_trip/mod.rs, tests/round_trip/section_flags.rs
This matches ELF and Mach-O behaviour.
Fixes #411
=> write/coff: `Section::flags` should override flags due `Section::kind`

src/write/macho.rs
For now only relocations with an addend of 0 are supported. In the future we could add support for arbitrary added using `ARM64_RELOC_ADDEND`.
This PR also allows the use of arbitrary Mach-O relocations on unsupported architectures, like we already do for ELF.
=> Support ARM64 relocations when writing a Mach-O object

src/write/coff.rs, src/write/mod.rs
This is needed to export symbols with `SymbolScope::Dynamic` from a DLL.
=> Build a .drectve section in COFF objects with export directives

src/read/pe/section.rs
Hello,
Here are a few utility functions that I'm currently using in my own projects, but that I think everyone could benefit from, so this could make sense to upstream them :-)
=> Added PE utils for sections and directories

Cargo.toml
Per <https://doc.rust-lang.org/cargo/reference/manifest.html#slash>
> Previously multiple licenses could be separated with a /, but that usage is deprecated.
I'm pretty sure that your intention is OR rather than AND: I guess this form improves by making that clear
=> disambiguate license

crates/examples/src/readobj/pe.rs, crates/examples/testfiles/pe/base-gnu.exe.readobj, src/pe.rs, src/read/pe/data_directory.rs, src/read/pe/mod.rs, src/read/pe/resource.rs
Add new API to allow walking the resource directory inside a PE file.
The entry point is `PeFile::resource_directory_table(&self) -> Result<ResourceDirectoryTable<'data>>`, from there it offers an iterator to visit every entries in the directory (`ResourceDirectoryTable::iter(&self) -> impl Iterator<Item = ResourceDirectoryEntry<'data>>`).
The API is mostly lazy, only reading data as needed (doesn't read entries and sub-directories data unless visited).
Also add a small binary `perscdump` as an example which print the resource data tree.
=> Add helper for walking the resource directory inside a PE file

crates/examples/src/readobj/pe.rs, crates/examples/testfiles/pe/base-gnu.exe.readobj, src/pe.rs, src/read/pe/data_directory.rs, src/read/pe/resource.rs
No major changes here, mostly just reorganizing or renaming for consistency and to fit my mental model: the resource section is a directory that contains a tree of tables and data entries.
I removed `language_code` because it's the same as `name_or_id().id()`, but let me know if you still want it.
cc @Guiguiprim
=> read/pe: style changes for resource parsing

src/pe.rs, src/read/coff/relocation.rs, src/write/coff.rs
This change adds support for reading and writing some COFF relocations for ARM and ARM64, based on their descriptions at https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#coff-relocations-object-only.
I've implemented this mainly to help me work with resources in ARM64 cross-compilation builds, which use `IMAGE_REL_ARM64_ADDR32NB`. I've tested this manually by comparing against the output of `llvm-windres` and `cvtres`.
=> read/coff, write/coff: support some ARM relocations

crates/examples/src/readobj/elf.rs
Add loongarch64 support in examples.
Added test files: https://github.com/zhaixiaojuan/object-testfiles/commit/088cf625d14b776dee02b499838b0a3ce7b3fc8f
=> Add loongarch64 examples

crates/examples/src/readobj/elf.rs, crates/examples/testfiles/elf/nostd-mipsel.o.readobj, crates/examples/testfiles/elf/nostd-mipsel.readobj, src/elf.rs
This adds a few constants that are needed to fix some targets that are broken on nightly rustc. Values were taken from the [LLVM source](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/BinaryFormat/ELF.h#L518-L521).
=> elf: add EF_MIPS_ABI_* e_flags constants

crates/examples/testfiles/elf/base-strip.objdump, crates/examples/testfiles/elf/base.o.objdump, crates/examples/testfiles/elf/base.objdump, src/common.rs, src/read/elf/file.rs, src/write/elf/object.rs
We need to be able to set the OS/ABI of ELF objects in rustc: https://github.com/rust-lang/rust/issues/97535#issuecomment-1141198653
Is this approach okay for you?
=> FileFlags::Elf: Add os_abi

src/read/elf/file.rs
Return `None` from `ElfFile::symbol_table` and `ElfFile::dynamic_symbol_table` if the tables are empty.
Fixes https://github.com/gimli-rs/addr2line/issues/250
=> read/elf: handle empty symbol tables

.github/workflows/rust.yml, Cargo.toml, README.md, src/lib.rs
=> Update hashbrown dependency

crates/examples/src/readobj/pe.rs, src/pe.rs, src/read/pe/data_directory.rs, src/read/pe/import.rs
This PR add support for the delay load import table: https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#delay-load-import-tables-image-only
This is mostly copied from the import table implementation, and re-uses the thunks implem from it.
I'm not certain about the naming, between "delay load" & "delay load import".
=> Add pe module delay load imports

src/read/macho/load_command.rs
This makes it easier to access some of the loadcommand structures. For instance, [`DylibCommand`](https://docs.rs/object/latest/object/macho/struct.DylibCommand.html) contains an [`LcStr`](https://docs.rs/object/latest/object/macho/struct.LcStr.html), which is defined as an offset from the start of the loadcommand, and is contained within the loadcommand data.
With the `raw_data()` function, we could trivially access it from a `LoadCommandData` by doing
```rust
let cmd: LoadCommandData = todo!();
let dylib = cmd.dylib().unwrap();
let dylib_name = cmd.raw_data.get(dylib.dylib.name.offset.get(endian)..);
```
=> Allow access to LoadCommandData's internal data

src/read/pe/file.rs
There can be more than one ImageDebugDirectory entries, and any of those
can be the CodeView record we are looking for.
=> fix: Search all ImageDebugDirectory entries for CodeView records

.github/workflows/rust.yml, README.md, crates/examples/src/readobj/elf.rs, crates/examples/testfiles/pe/resource.exe.readobj.0, src/read/elf/symbol.rs, src/read/pe/resource.rs
We were reading the ELF extended section indices and the PE resource names using native endian.
These fixes are breaking changes, and also update the required rust version to 1.52.0 (for UTF-16 parsing).
Also add 32-bit and big endian targets to CI.
Fixes #456
=> read: fix endianness problems

src/elf.rs
The use of pcalau12i and related relocations for PC-relative addressing
is a little tricky on LoongArch.  Define "PC-relative anchor" explicitly
to make their semantics more clear.
=> elf: fix documentation for LoongArch "PCALA" style relocations

src/read/macho/fat.rs, src/read/macho/file.rs, src/write/macho.rs
Add parsing for the powerpc and powerpc64 architecture types on the macho object type.
=> Add powerpc handling macho.

Cargo.toml, src/common.rs, src/lib.rs, src/xcoff.rs
The XCOFF is the object file format for AIX. (XCOFF doc: https://www.ibm.com/docs/en/aix/7.2?topic=formats-xcoff-object-file-format)
This PR adds the basic definition of XCOFF.
Future PRs will initialize support for reading and writing XCOFF.
=> Initial support for XCOFF: add basic definitions.

src/archive.rs, src/read/archive.rs
The archive format on AIX is called 'big archive' (see definition at https://www.ibm.com/docs/en/aix/7.3?topic=formats-ar-file-format-big), which is quite different from BSD and GNU variants.
This PR will add support for reading it, as part of the efforts porting Rust toolchain onto AIX. (Writing facility was done by wrapping LLVM upstream code in https://github.com/rust-lang/ar_archive_writer/pull/2)
Also thanks to contribution from @jsji.
=> Support reading AIX big archive format

src/archive.rs, src/read/archive.rs
This is from review of #462. Iterating over members by member table can avoid potential infinite loop if the file is malformed. Also, this change sets `names` for a parsed file.
=> read/archive: locate members by table in AIX archive

src/write/macho.rs, src/write/mod.rs
This PR adds support for relocations with  `RelocationEncoding::Aarch64Call`  on Mach-O. Before this PR we would error out, as the relocation has a size of 26 which was unhandled, and we weren't setting the appropriate `r_type`. After this PR we support relocations with `RelocationEncoding::Aarch64Call` and an arbitrary addend.
This PR also handles a few extra cases of the relocation size (21 and 12) in order to support the usage of Mach-O specific relocations like `ARM64_RELOC_PAGE21` and `ARM64_RELOC_PAGEOFF12`, respectively.
=> Support Aarch64Call relocations for Mach-O

crates/examples/src/bin/dyldcachedump.rs
```bash
$ ls -l /System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/
total 7706920
-rwxr-xr-x  1 root  admin   802367771 Sep 24 00:00 aot_shared_cache.0
-rwxr-xr-x  1 root  admin   956507291 Sep 24 00:00 aot_shared_cache.1
-rwxr-xr-x  1 root  admin   910736027 Sep 24 00:00 aot_shared_cache.2
-rwxr-xr-x  1 root  admin   890360219 Sep 24 00:00 aot_shared_cache.3
-rwxr-xr-x  1 root  admin   129487259 Sep 24 00:00 aot_shared_cache.4
-rwxr-xr-x  1 root  admin  1600995328 Sep 24 00:00 dyld_shared_cache_arm64e
-rwxr-xr-x  1 root  admin  1671282688 Sep 24 00:00 dyld_shared_cache_arm64e.01
-rwxr-xr-x  1 root  admin      933245 Sep 24 00:00 dyld_shared_cache_arm64e.map
-rwxr-xr-x  1 root  admin   811483136 Sep 24 00:00 dyld_shared_cache_x86_64
-rwxr-xr-x  1 root  admin   800620544 Sep 24 00:00 …
```
=> examples/dyldcachedump: fix finding dyld subcaches on macOS 13

src/archive.rs, src/read/archive.rs
- Include magic in `AixFileHeader`.
- Move AIX file header parsing into separate function.
- Use `ArchiveMember::parse_aixbig` to parse the members for the symbol tables and member index.
- Add `Members` enum for `ArchiveFile::members` instead of overloading the meaning of fields.
- Fix length of member index count (20 instead of 30).
- Add `AixMemberOffset` to simplify member index parsing.
- Read the entire member index array at once. This avoids some overflow checking.
- Don't set `ArchiveFile::names` since it isn't used.
Followup to #467. @ecnelises Can you test and review please?
=> read/archive: AIX big archive enhancements

src/write/coff.rs
MSVC's linker really dislikes many different section names, print out all sections with the same name, which seems to work better.
Closes #474
=> write/coff: Duplicate section names

src/common.rs, src/elf.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/write/elf/object.rs, tests/round_trip/mod.rs
This PR adds the bare minimum Xtensa support to allow our [Xtensa-enabled Rust fork](https://github.com/esp-rs/rust) to compile on stable 1.65, as we were running into https://github.com/rust-lang/rust/issues/102290 in our testing.
=> Initial Xtensa support

crates/examples/src/readobj/elf.rs, src/elf.rs
In a revision of LoongArch ELF ABI [1], it was decided that ILP32 objects must use ELFCLASS32.  Now both LP64D and ILP32D will use the same number (0x1) for "double float", so EF_LARCH_ABI_LP64{S,F,D} are renamed and EF_LARCH_ABI_ILP32{S,F,D} are removed.
The change is ABI-compatible for LP64, but not API-compatible.  ILP32 is not supported by GCC and Glibc yet so it's not really used anyway.
And, a seperate bit is allocated to indicate if the ELF object file uses any relocation type directly writing to immediate slots [2].
Update the code to match these changes.
[1]:https://github.com/loongson/LoongArch-Documentation/pull/47/files#diff-711b3e7b6a005b492898ac6d93f2d8d37c00e0831e210993a6f9dbb26c043717 [2]:https://github.com/loongson/LoongArch-Documentation/pull/61/files#diff-711b3e7b6a005b4 …
=> elf: Update LoongArch eflags

src/read/pe/resource.rs
In my program, I want to give access to the bytes of a resource name. Since this is a unicode string, there is already a method to get a slice of u16. I can use it to get back the raw bytes, but that requires unsafe code that can be avoided by getting the raw bytes.
So this PR adds a new method to ResourceName to get the name as a slice of bytes instead of a slice of u16.
=> feat: add ResourceName::raw_data method

.github/workflows/rust.yml, Cargo.toml, crates/examples/Cargo.toml, crates/examples/tests/testfiles.rs, src/lib.rs
The xcoff feature needs further work before being ready for release.
Also, the default resolver can be changed to "2" now that the MSRV is at least 1.51. This works better with features in workspaces.
cc @EsmeYi
=> Change xcoff to be an unstable feature

src/common.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/write/elf/object.rs, tests/round_trip/mod.rs
This is needed for the `aarch64-unknown-linux-gnu_ilp32` target in rustc.
I've only implemented minimal support for ILP32 relocations since rustc doesn't use these (it only generates object files to wrap metadata or to force the linker to import symbols).
=> Add support for AArch64 ILP32 for ELF

crates/examples/testfiles/elf/base.o.objdump, crates/examples/testfiles/elf/base.objdump, src/read/elf/symbol.rs
This makes 2 changes to `SymbolKind` detection:
- `STT_NOTYPE` is detected as a label, since that's the default type given to a label in assembly code. This is also used for mapping symbols that are inserted by the assembler to indicate which addresses contain code or data.
- `STT_GNU_IFUNC` is detected as a function symbol.
=> Detect more ELF symbol kinds

src/elf.rs
Constants are sourced from `binutils-2.39/include/elf/avr.h`
=> Add AVR e_flags constants and more relocation types

src/common.rs, src/write/coff.rs, src/write/elf/object.rs, src/write/macho.rs, src/write/mod.rs
👋 Hey,
This PR adds a `SectionKind::ReadOnlyDataWithRel`. For MachO and COFF it is essentially the same as ReadOnlyData.
=> write: Add `SectionKind::ReadOnlyDataWithRel`

crates/examples/src/readobj/elf.rs, src/elf.rs
For targeting the RV32E base ISA. From
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/079772828bd10933d34121117a222b4cc0ee2200/riscv-elf.adoc
=> Add ELF RISCV_RVE for E ABI

crates/examples/src/bin/elfcopy.rs
I know that elfcopy is supposed to be a reader/writer example for ELF files, but I found it was the only tool that would let me redefine symbols in shared libraries. I think there is some serious value in having a tool that does this, especially since the way other objcopy implementations work makes it basically impossible to implement something like this easily.
If you'd like elfcopy to remain a basic copy example without command line arguments I'll understand. I originally made this a [standalone](https://github.com/amshafer/elfcopy) repo, but I'd like to contribute it back as I personally found it pretty lifesaving. Thanks and love the toolkit!
---
This commit makes elfcopy the only tool I'm aware of that will let you rename symbols in dynamic libraries. Other tools like objcopy will …
=> elfcopy: Add --redefine-syms <file> arguments

crates/examples/src/objdump.rs, src/read/macho/load_command.rs, src/read/macho/section.rs
=> read/macho: handle invalid cmdsize and section align

src/write/elf/writer.rs
if we copy a elf with a empty section and the sh_addralign(align_start) is not 0, it will return a unaligned offset.
=> write: fix reserving empty section error

crates/examples/src/bin/elfcopy.rs, src/read/elf/attributes.rs, src/read/elf/mod.rs, src/read/elf/section.rs, src/write/elf/writer.rs
This adds partial support for `SHT_GNU_ATTRIBUTES` sections, which is of primary importance on powerpc systems since the endianness is specified as a file tag. For example see the [Tag_GNU_Power_ABI_FP](https://sourceware.org/binutils/docs/as/GNU-Object-Attributes.html) tag.
The details on the section format can be found here in section 4.3.6: https://static1.squarespace.com/static/59c4375b8a02c798d1cce06f/t/59d55a5a32601e2413a23988/1507154526861/ELF+for+ARM.pdf
This series only handles *file* tags, since they are the most straightforward. The symbol and section tag format requires being able to interact with ULEB128-encoded values, which I did not find an easy way to do without bringing in lots of third party dependencies. The file tags are the most common however, and paired with #508 …
=> Add support for .gnu.attributes sections

src/write/macho.rs
Apple defines a bunch of segments:sections, it is tedious to deal with all of them. Symbols from unknown sections are flagged as unknown, leading to the inability to write it using the `writer` module.
This commit removes the check that requires symbol to be known for macho.
(See https://github.com/gimli-rs/object/pull/517 for more information).
=> Accept `SymbolKind::Unknown` for macho when writing an object.

crates/examples/src/bin/elfcopy.rs, crates/examples/src/readobj/elf.rs, crates/examples/testfiles/elf/base-mips64el.o.readobj, crates/examples/testfiles/elf/base-mips64el.readobj, src/elf.rs, src/read/elf/attributes.rs, src/read/elf/section.rs, src/read/util.rs, src/write/elf/writer.rs, src/write/util.rs
- read: add iterator for section and symbol indices
- read: add AttributeReader for parsing attribute data
- write: add AttributesWriter for building the attributes section
- elfcopy: convert section and symbol indices
- elfcopy: handle attributes sections in object files
- readobj: print some contents of attributes sections
=> elf: improve attributes section support

src/write/macho.rs, src/write/mod.rs
Needed to fix https://github.com/rust-lang/rust/issues/106021.
Unsure if this API is right, though.
=> Add support for writing a mach-o file with an `LC_BUILD_VERSION` command

Cargo.toml, crates/examples/Cargo.toml, crates/examples/src/bin/objcopy.rs, crates/examples/testfiles/xcoff/base.o.objdump, crates/examples/testfiles/xcoff/base.xcoff.objdump, crates/examples/testfiles/xcoff/base32.o.objdump, crates/examples/testfiles/xcoff/base32.xcoff.objdump, src/common.rs, src/lib.rs, src/read/any.rs, src/read/coff/symbol.rs, src/read/elf/symbol.rs, src/read/macho/symbol.rs, src/read/traits.rs, src/read/wasm.rs, src/read/xcoff/section.rs, src/read/xcoff/symbol.rs, src/write/mod.rs, src/write/xcoff.rs, tests/round_trip/mod.rs
See individual commits.
Please review @EsmeYi @bzEq
=> xcoff improvements

README.md, src/lib.rs, src/write/mod.rs
Clarify that write::Object is only for relocatable object files.
Add XCOFF where appropriate.
Closes #478
=> Update crate documentation

crates/examples/src/readobj/elf.rs, src/elf.rs
=> elf: add PT_GNU_PROPERTY

crates/examples/src/bin/pecopy.rs, crates/examples/src/readobj/mod.rs, crates/examples/src/readobj/pe.rs, crates/examples/testfiles/pe/base-bigobj.o.objdump, crates/examples/testfiles/pe/base-bigobj.o.readobj, crates/examples/testfiles/pe/base-bigobj.obj.objdump, crates/examples/testfiles/pe/base-bigobj.obj.readobj, crates/examples/testfiles/pe/base-gnu.exe.readobj, src/endian.rs, src/pe.rs, src/read/any.rs, src/read/coff/comdat.rs, src/read/coff/file.rs, src/read/coff/relocation.rs, src/read/coff/section.rs, src/read/coff/symbol.rs, src/read/mod.rs, src/write/coff.rs, tests/read/coff.rs
=> read: add COFF bigobj support

Cargo.toml, crates/examples/src/readobj/elf.rs, crates/examples/testfiles/elf/base-debug-zlib.o.readobj.compression, crates/examples/testfiles/elf/base-debug-zstd.o.readobj.compression, src/elf.rs, src/read/elf/section.rs, src/read/mod.rs
Also add readobj support for compression headers.
Closes #463
=> elf: add ELFCOMPRESS_ZSTD

src/read/traits.rs
This is an unreleased API. It seems too specialized, the function signature isn't ideal, and the semantics weren't fully documented.
=> read: delete symbol_address_by_name

src/read/wasm.rs
=> Try to guess symbol address in Wasm

crates/examples/testfiles/wasm/global-wasm32.objdump, crates/examples/testfiles/wasm/global-wasm64-import.objdump, crates/examples/testfiles/wasm/global-wasm64.objdump, src/common.rs, src/read/wasm.rs
Also add test files for globals.
=> read/wasm: add support for wasm64

src/write/elf/object.rs, tests/aligned_sections.rs
This was previously causing an assertion failure because the alignment padding was not written to the buffer if the section was empty, which caused subsequent sections to be placed at the wrong offsets.
=> Fix writing of aligned empty sections

src/write/macho.rs
as used by arm64_32-apple-watchos compile target (tier 3 platform).
Rust issue: https://github.com/rust-lang/rust/issues/111217
=> Support Aarch64_Ilp32 architecture for mac 

src/write/macho.rs, tests/round_trip/macho.rs
=> write/macho: ensure padding matches for section file offset and address

crates/examples/src/objdump.rs, crates/examples/testfiles/coff/import_msvc.lib.objdump, src/read/coff/import.rs, src/read/coff/mod.rs, src/read/mod.rs
See #512.
This adds some support for reading [short import library files](https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#import-library-format). These only appear in archives and are Windows specific. Unlike most other content of `.lib` archives, these are not object files. Instead they are a header that minimal describes how the linker should update the `.idata` section (aka DLL import tables) for a specific symbol. This header is followed by two strings: the DLL name and the public symbol name. Note that according to [a comment in src/pe.rs](https://github.com/gimli-rs/object/blob/60c9721884055533e54084c00fd03e88c1dc1cc1/src/pe.rs#L2888) there can also be a third string, though I can't find this documented anywhere. In any case supporting it isn't difficult.
I've added …
=> Read short import files

crates/examples/src/objdump.rs, crates/examples/src/readobj/mod.rs, crates/examples/src/readobj/pe.rs, crates/examples/testfiles/coff/import_msvc.lib.readobj, src/pe.rs, src/read/coff/import.rs, src/read/mod.rs
Add lower level parsing support for ImportObjectHeader and use it in the readobj example.
Also some style changes for the import object file support.
cc @ChrisDenton
=> read/coff: lower level parsing support for ImportObjectHeader

.github/workflows/rust.yml
mips64 isn't available currently.
=> ci: switch to powerpc64 for big endian test

src/elf.rs, src/write/coff.rs, src/write/elf/object.rs, src/write/macho.rs, src/write/mod.rs, src/write/xcoff.rs
=> Support the arm64e architecture for macOS/iOS

src/elf.rs, src/read/elf/relocation.rs
R_LARCH_CFA is documented "reserved" because nothing generates or processes it for now.
Link: https://github.com/loongson/la-abi-specs/releases/v2.10
=> elf: Add LoongArch relocation types introduced in LoongArch ABI v2.10

crates/examples/Cargo.toml, crates/examples/src/bin/objcopy.rs, crates/examples/src/lib.rs, crates/examples/src/objcopy.rs, crates/examples/testfiles/macho/base-aarch64.o.objcopy, crates/examples/testfiles/macho/base-x86_64.o.objcopy, crates/examples/testfiles/macho/reloc-aarch64.o.objcopy, crates/examples/testfiles/macho/reloc-x86_64.o.objcopy, crates/examples/tests/testfiles.rs
Currently only x86-64 and AArch64 work.
i386 and ARM are missing support for scattered relocations and paired relocations.
Also add support for an environment called OBJECT_TESTFILES_UPDATE which causes the tests to update the output files.
=> macho: add some objcopy tests

crates/examples/src/objcopy.rs, crates/examples/testfiles/macho/base-aarch64.o.objcopy, crates/examples/testfiles/macho/base-x86_64.o.objcopy, crates/examples/testfiles/macho/reloc-aarch64.o.objcopy, crates/examples/testfiles/macho/reloc-x86_64.o.objcopy, src/read/macho/file.rs, src/read/macho/load_command.rs, src/write/macho.rs, tests/round_trip/macho.rs, tests/round_trip/tls.rs
After this, the output of objcopy is identical to the input for the test files that are updated by this pull request.
=> write/macho: change output to more closely match LLVM

crates/examples/src/readobj/elf.rs, src/elf.rs, src/write/elf/object.rs
- R_LARCH_DELETE is reserved by the ABI now (the BFD linker will stop using it for relaxation as well).
- R_LARCH_CALL36 is added for function calls under medium code model.
Link: https://github.com/loongson/la-abi-specs/releases/v2.20
Link: https://sourceware.org/pipermail/binutils/2023-October/129938.html
=> elf: Update LoongArch relocation types per LoongArch ABI v2.20

src/write/elf/object.rs
This matches the behaviour of gcc and clang, and allows us to remove the hack to change relocations to use section symbols.
I've tested that rustc_codegen_cranelift's test.sh works when running under x86-64 linux. 
Closes #587
=> write/elf: x86-64 branches should always use R_X86_64_PLT32

crates/examples/testfiles/coff/import_msvc.lib.objdump, src/read/coff/symbol.rs
Common symbols should be IMAGE_SYM_CLASS_EXTERNAL.
We were also matching on IMAGE_SYM_CLASS_SECTION, which can occur for section symbols in import libraries where the section is defined in another archive member.
=> read/coff: SymbolKind::Common detection was too broad

crates/examples/testfiles/pe/base-bigobj.o.objdump, crates/examples/testfiles/pe/base-gnu.exe.objdump, crates/examples/testfiles/pe/base-gnu.exe.readobj, crates/examples/testfiles/pe/base.o.objdump, src/read/coff/symbol.rs
Previously we wrongly excluded section symbols with non-zero values, and wrongly included function symbols with zero values.
This also means that we give them correct symbol kind, and that we exclude them from the symbol map.
Note that we still don't give the correct symbol kind to section symbols that don't have an auxiliary symbol.
=> read/coff: improve detection of auxiliary symbols for sections

.github/workflows/rust.yml
Update [`actions/checkout`](https://github.com/actions/checkout) to v4, it's current version.
Changelog:
> ## v4.1.0
> - Add support for partial checkout filters
>
> ## v4.0.0
> - Support fetching without the --progress option
> - Update to node20
=> ci: update actions/checkout in GitHub Actions workflows to v4

src/read/any.rs, src/read/coff/file.rs, src/read/coff/import.rs, src/read/elf/file.rs, src/read/elf/hash.rs, src/read/elf/symbol.rs, src/read/macho/dyld_cache.rs, src/read/macho/fat.rs, src/read/macho/file.rs, src/read/mod.rs, src/read/pe/data_directory.rs, src/read/pe/export.rs, src/read/pe/file.rs, src/read/pe/import.rs, src/read/pe/resource.rs, src/read/pe/rich.rs, src/read/traits.rs, src/read/util.rs, src/read/xcoff/comdat.rs, src/read/xcoff/file.rs, src/read/xcoff/relocation.rs, src/read/xcoff/section.rs, src/read/xcoff/segment.rs, src/read/xcoff/symbol.rs, src/write/elf/object.rs, src/write/macho.rs, src/write/mod.rs, src/write/xcoff.rs
The exception is reusing common definitions that are reexported in the read module (preexisting) and write module (newly added).
This is for consistency, and makes it easier to experiment with a restructure.
=> Avoid using reexports within the crate

crates/examples/src/objdump.rs, crates/examples/src/readobj/macho.rs, src/read/macho/fat.rs, src/read/mod.rs
My primary motivation is to avoid the impl for a type in another module, but I think this is also closer to the API for other files.
=> read: add MachOFatFile

src/read/mod.rs
This was removed in eb58357f for consistency (nowhere else in the read API allows mutation), but there are existing users so add it back in for convenience.
=> read: add Relocation::set_addend

src/read/read_cache.rs, tests/read/elf.rs, tests/read/mod.rs
related to #204
added a regression test case which used to attempt to allocate 5 exabytes of memory.
test files added in https://github.com/gimli-rs/object-testfiles/pull/12
=> read: check that sizes are smaller than the file when reading

src/read/mod.rs, src/read/read_cache.rs
This changes the buffers allocated in ReadCache and for decompression.
This would also cause the test added in #630 to pass (it's still better to have the fix in #630 though).
Closes #204
=> read: use Vec::try_reserve_exact for large allocations

crates/examples/src/bin/dyldcachedump.rs, crates/examples/src/bin/objdump.rs, crates/examples/src/objdump.rs, src/macho.rs, src/read/macho/dyld_cache.rs
This allows successful parsing of dyld caches on macOS 13 and above on Intel Macs.
The main dyld cache file on macOS contains an array of subcache info structs, each of which specifies the UUID (and some other information) of each subcache.
`DyldCache::parse` checks that the subcache UUIDs match these expected UUIDs.
In macOS 13, the format of the subcache info struct changed: the struct gained an additional field after the UUID field. This means that as soon as you had more than one subcache, our UUID check would fail, because the second subcache UUID would be read from the wrong offset.
I didn't notice this on my Apple Silicon Mac, because the arm64e dyld cache only has one subcache:
`dyld_shared_cache_arm64e.01`.
But on Intel Macs, there are currently four subcaches: …
=> Correctly handle dyld caches on macOS 13 and above

src/build/elf.rs, tests/build/elf.rs, tests/build/mod.rs, tests/integration.rs
=> build/elf: improve handling of sh_offset for SHT_NOBITS when writing

crates/examples/src/readobj/elf.rs, crates/examples/testfiles/elf/base-aarch64.o.readobj, crates/examples/testfiles/elf/base-aarch64.readobj, crates/examples/testfiles/elf/base-mips64el.o.readobj, crates/examples/testfiles/elf/base-mips64el.readobj, crates/examples/testfiles/elf/base.o.readobj, crates/examples/testfiles/elf/base.readobj, crates/examples/testfiles/elf/nostd-mipsel.o.readobj, crates/examples/testfiles/elf/nostd-mipsel.readobj, crates/rewrite/testfiles/elf/base.delete-symbol, crates/rewrite/testfiles/elf/base.noop, crates/rewrite/testfiles/elf/base.rename-symbol, src/build/elf.rs, src/read/elf/section.rs, src/write/elf/writer.rs, tests/build/elf.rs
.dynstr doesn't need to be present if there are no dynamic strings.
- handle section index 0 in read::elf::SectionTable::strings
- don't require .dynstr when writing if there are no strings
- don't print name of symbol index 0 in readobj example
=> elf: allow for absence of dynstr

src/read/mod.rs, src/read/wasm.rs
Encountered in https://github.com/bytecodealliance/wasmtime/pull/8055#issuecomment-2008353550
=> read/wasm: multiple fixes

crates/examples/src/readobj/mod.rs, src/read/archive.rs, src/read/mod.rs
=> read/archive: add thin archive support

src/read/mod.rs, src/read/read_cache.rs
=> read: allow use of ReadCache without std

src/read/any.rs, src/read/coff/section.rs, src/read/elf/section.rs, src/read/macho/section.rs, src/read/mod.rs, src/read/pe/section.rs, src/read/traits.rs, src/read/wasm.rs, src/read/xcoff/section.rs
This is intended to handle relocations for DWARF.
=> read: add ObjectSection::relocation_map

src/build/elf.rs
=> build/elf: don't require the same alignment for all load segments

src/read/archive.rs
Arm64EC introduced a new special member in COFF called `/<ECSYMBOL>/` which contains the symbol table for EC-specific symbols: <https://github.com/llvm/llvm-project/blob/1aceee7bb6c4423da73f71aff2004493bdf620d1/llvm/lib/Object/ArchiveWriter.cpp#L647>
When parsing an archive, `object` should skip over this member.
=> Skip the EC Symbol Map when parsing COFF archives

src/pod.rs, src/read/elf/section.rs, src/read/elf/segment.rs, src/read/pe/file.rs
Also convert some code to use it.
=> pod: add slice_from_all_bytes{_mut}

src/read/macho/file.rs, src/read/macho/section.rs, src/read/macho/segment.rs
Note that this is only for operations on the segment itself. Sections within the segment were already using the correct data.
=> read/macho: fix data for segments in dyld caches

src/read/mod.rs
These are commonly used for DWARF sections in Mach-O.
=> read: support section targets in RelocationMap

crates/examples/src/bin/simple_write.rs, src/write/macho.rs, src/write/mod.rs, tests/round_trip/comdat.rs, tests/round_trip/elf.rs
For Mach-O, `add_symbol_data` now ensures that the symbol size is at least 1 when subsections via symbols are enabled. This change was made to support linking with ld-prime. It is also unclear how this previously managed to work with ld64.
`write::Object::add_subsection` no longer enables subsections via symbols for Mach-O. Use `set_subsections_via_symbols` instead. This change was made because Mach-O subsections are all or nothing, so this decision must be made before any symbols are added.
`write::Object::add_subsection` no longer adds data to the subsection. This change was made because it was done with `append_section_data`, but this is often not the correct way to add data to the subsection. Usually `add_symbol_data` is a better choice.
=> write/macho: ensure Mach-O subsections are not zero size

crates/examples/src/objcopy.rs, crates/examples/testfiles/elf/base-aarch64.o.objdump, crates/examples/testfiles/elf/base-aarch64.objdump, crates/examples/testfiles/elf/base.o.objdump, crates/examples/testfiles/elf/base.objdump, src/common.rs, src/read/elf/comdat.rs, src/read/elf/file.rs, src/read/elf/section.rs, src/read/elf/symbol.rs, src/read/xcoff/symbol.rs, src/write/coff/object.rs, src/write/elf/object.rs, src/write/macho.rs, src/write/xcoff.rs, tests/round_trip/bss.rs, tests/round_trip/comdat.rs, tests/round_trip/common.rs, tests/round_trip/elf.rs, tests/round_trip/mod.rs, tests/round_trip/section_flags.rs, tests/round_trip/tls.rs
This affects ELF and XCOFF, including some of the lower level APIs too.
=> read: do not return null sections or symbols in unified API

src/read/elf/section.rs, src/read/elf/symbol.rs
While these should be true in practice, they aren't needed, and their presence may require callers to annotate them too.
=> read/elf: remove unneeded lifetimes

crates/examples/src/bin/pecopy.rs, crates/examples/src/objdump.rs, crates/examples/src/readobj/elf.rs, crates/examples/src/readobj/pe.rs, crates/examples/src/readobj/xcoff.rs, src/build/elf.rs, src/read/coff/comdat.rs, src/read/coff/file.rs, src/read/coff/section.rs, src/read/coff/symbol.rs, src/read/elf/comdat.rs, src/read/elf/file.rs, src/read/elf/hash.rs, src/read/elf/relocation.rs, src/read/elf/section.rs, src/read/elf/symbol.rs, src/read/elf/version.rs, src/read/macho/file.rs, src/read/macho/symbol.rs, src/read/mod.rs, src/read/pe/file.rs, src/read/xcoff/file.rs, src/read/xcoff/symbol.rs
Note that many APIs returned unvalidated indices. Validation is performed when they are used to access a table entry. For cases where a 0 index is normal, an Option may be returned.
=> read: use SectionIndex/SymbolIndex in low level API

src/read/elf/file.rs, src/read/elf/relocation.rs, src/read/elf/section.rs, src/read/elf/symbol.rs
Implement Default for SectionTable and RelocationSections. Return a SectionIndex from SectionTable::section_by_name. Add some helpers to Sym trait.
=> read/elf: small fixes to low level API

crates/examples/src/readobj/pe.rs, crates/examples/src/readobj/xcoff.rs, src/read/coff/relocation.rs, src/read/coff/symbol.rs, src/read/xcoff/relocation.rs, src/read/xcoff/symbol.rs
=> read: add more helpers for SymbolIndex and SectionIndex

crates/examples/testfiles/elf/base-aarch64.objdump, crates/examples/testfiles/elf/base.objdump, src/read/elf/file.rs, src/read/elf/version.rs
This change parses the library name for a dynamic symbol from the ELF symbol versioning table and removes a // TODO
=> elf: parse library from symbol versioning table

src/read/elf/section.rs, src/read/gnu_compression.rs, src/read/macho/file.rs, src/read/macho/section.rs, src/read/mod.rs, src/read/traits.rs, tests/read/macho.rs, tests/read/mod.rs
This PR adds support in the object crate for Go's format to compress Mach-O debug info sections. It contains two changes:
* The MachOFile now can match section names which contain both the `__` and `__z` prefix instead of a `.`.
* The MachOSection now detects the presence of the `__z` prefix and attempts to offer decompression when it detects the section is compressed using the Go compression scheme.
A third commit adds testing. This third commit will need to be rebased to update the testfiles commit once https://github.com/gimli-rs/object-testfiles/pull/14 is merged into the upstream.
Fixes https://github.com/gimli-rs/object/issues/696.
=> read/macho: support Go's compression format

src/common.rs, src/write/coff/object.rs, src/write/elf/object.rs, src/write/macho.rs, src/write/xcoff.rs
For ELF, DWARF string sections need different flags.
=> Add SectionKind::DebugString

crates/examples/src/objcopy.rs, src/write/macho.rs, tests/round_trip/mod.rs, tests/round_trip/tls.rs
This prevents a crash of Apple's new linker.
=> Reverse the order of emitting relocations on MachO

crates/rewrite/testfiles/elf/libbase.so.noop, crates/rewrite/tests/testfiles.rs, src/build/elf.rs, src/write/elf/writer.rs
This handles the common case where there are only two version definitions which have the same name.
When rewriting files, we are required to optimise at least as well as the original file so that it fits in the allocated space.
=> build/elf: optimise output of version definitions

crates/rewrite/testfiles/elf/base.add-needed, crates/rewrite/testfiles/elf/base.add-rpath, crates/rewrite/testfiles/elf/base.add-runpath, crates/rewrite/testfiles/elf/base.delete-needed, crates/rewrite/testfiles/elf/base.delete-section, crates/rewrite/testfiles/elf/base.delete-symbol, crates/rewrite/testfiles/elf/base.noop, crates/rewrite/testfiles/elf/base.rename-section, crates/rewrite/testfiles/elf/base.rename-symbol, crates/rewrite/testfiles/elf/base.replace-needed, crates/rewrite/testfiles/elf/base.set-interpreter, crates/rewrite/testfiles/elf/base.set-runpath, src/write/elf/writer.rs
=> write/elf: fix alignment for SHT_HASH/SHT_GNU_verdef/SHT_GNU_verneed

src/write/elf/writer.rs, tests/round_trip/elf.rs
Previously, if the symtab was empty then we were writing a strtab that had 0 bytes of data. This gives a linker error:
`SHT_STRTAB string table section [index 4] is empty`
Also, if there is a symtab then there must be a strtab, otherwise the error is:
`invalid sh_type for string table section [index 0]: expected SHT_STRTAB, but got SHT_NULL`
Closes #709
=> write/elf: fix writing of strtab when symtab is empty

src/endian.rs
These functions are all trivially `const`. Having a `const` way to construct these types allows for a safe way of constructing them in a `static` or `const` item.
=> Make `from_bytes` integer constructors `const`

src/read/elf/attributes.rs, src/read/elf/note.rs, src/read/elf/version.rs, src/read/macho/load_command.rs, src/read/pe/import.rs, src/read/pe/relocation.rs
This also changes the underlying `next` methods to fuse on error.
=> read: implement Iterator for more types

Cargo.lock, Cargo.toml
The latest `wasmparser` includes a licensing change from Apache-2.0 with the LLVM exception to Apache-2.0 with the exception, or vanilla Apache-2.0, or MIT.
Update to the latest version, which makes figuring out licensing a bit easier for dependents of `object`.
=> Update `wasmparser` to the latest version

src/pe.rs
Listed in [`km/ntimage.h`](https://github.com/microsoft/wdkmetadata/blob/99192741981aa7b7dc7db4aca3401f5d20496c91/generation/WDK/IdlHeaders/km/ntimage.h#L245-L247)
=> Add new pe::IMAGE_FILE_MACHINE_ constants

src/write/coff/object.rs, tests/round_trip/bss.rs
Some compilers generate section symbols for the BSS section, which is then used with relocations in other sections.
This causes a panic on the current version since the checksum is done on `section.data()`, which fails the assertion `!self.is_bss()`.
With this, I am setting the checksum of a BSS section to 0, which it is also set to with the compiler I am using.
=> write/coff: Set checksum for BSS section symbols

crates/examples/src/readobj/elf.rs, crates/examples/testfiles/elf/nostd-mipsel.o.readobj, src/elf.rs
There constants were added recently in `2.43` (https://github.com/bminor/binutils-gdb/blob/f9b44496e631edfa5c8218699d5a5ffe59b21033/include/elf/common.h#L613C37-L614).
=> Add 2 new  constants

src/read/mod.rs
The PR verifies that the uncompressed data matches the declared size in the compression section header.
=> Add check for uncompressed data

src/write/elf/object.rs
Reduce boilerplate code and reformat match for better readability.
=> Reformat code

src/read/mod.rs
As we discovered is necessary in rust-lang/backtrace-rs#626
=> read/elf: Read zstd frames in a loop until decompression is complete.

crates/rewrite/testfiles/elf/annobin-strtab, crates/rewrite/tests/testfiles.rs, src/build/elf.rs
=> build/elf: handle .annobin.notes string section

src/common.rs, src/read/elf/file.rs, src/write/elf/object.rs, tests/round_trip/mod.rs
This PR adds Mips N32, which is yet another ILP32 ABI.
=> Add Mips64 N32 ABI

crates/examples/src/readobj/elf.rs, crates/examples/testfiles/elf/base-relr-i686.objdump, crates/examples/testfiles/elf/base-relr-i686.readobj, crates/examples/testfiles/elf/base-relr-x86_64.objdump, crates/examples/testfiles/elf/base-relr-x86_64.readobj, crates/rewrite/testfiles/elf/base-relr-i686.noop, crates/rewrite/testfiles/elf/base-relr-x86_64.noop, crates/rewrite/tests/testfiles.rs, src/build/elf.rs, src/elf.rs, src/read/any.rs, src/read/coff/file.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/read/elf/section.rs, src/read/macho/file.rs, src/read/pe/file.rs, src/read/wasm.rs, src/read/xcoff/file.rs, src/write/elf/writer.rs
This adds a low level API for reading `SHT_RELR` relocations, and changes the ELF builder to copy the section.
This doesn't add the relocations to the `read::Object` trait. It's not clear what the best way to support this is. Adding them into `Object::dynamic_relocations` would require synthesizing fields of the `Relocation`. An alternative is to add a new method, and perhaps this method could cover PE base relocations (which are also not currently handled by the `read::Object` trait). This can wait until someone has a use case for these so that it can be tested properly.
In the future, the ELF builder may need to support modifying the relocations. The difficulty with this is that the relocations would need to be encoded again before doing layout. Again, this can wait until someone has a …
=> Initial SHT_RELR support

Cargo.toml, build.rs, src/build/error.rs, src/read/mod.rs, src/write/mod.rs
This commit updates when the `Error` trait is implemented to account for how in Rust 1.81-and-prior the `Error` trait is always available, even in `core`. This is currently done with detection at build-time of the current Rust compiler version because the MSRV for this crate is below 1.81. In the future when the MSRV is increased, however, the build script can be deleted.
=> Implement `core::error::Error` on Rust 1.81+

src/write/coff/object.rs, src/write/elf/object.rs
So rather than producing `.text.` it now produces `.text`
Fixes https://github.com/gimli-rs/object/issues/409
=> Skip . and $ in section name for subsections when an empty name is given

src/macho.rs, src/read/macho/dyld_cache.rs
=> macho: reorder dyld cache definitions

src/write/macho.rs
Desired by https://github.com/rust-lang/rust/pull/133832.
=> write/macho: support `ARM_RELOC_VANILLA`

src/read/read_ref.rs, tests/read/elf.rs
Hi, this PR changes the implementation of `read_bytes_at` in `ReadRef` for `&[u8]` to allow zero size reads for any offset, even if that offset is out of bounds.
This makes it match the behavior of `ReadRef` for `ReadCache`, and also makes e.g. `ElfSegment::bytes` work for zero sized segments as seen in real world ELF files.
Please let me know if you have any comments or would like me to change something, or if you want to keep the current behavior, I'm also happy to just carry this patch in a fork, or to add this behavior in a custom `ReadRef` implementation only, if there is some reason for disallowing zero sized reads that are out of bounds.
Commit message copied below with more detail:
------
Some ELF files do have segments with size zero, at offsets that are invalid / out of bounds. …
=> read_ref: allow zero size reads at any offset

src/read/archive.rs
This PR adds a [`.size_hint()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint) implementation to the `ArchiveSymbolIterator`.
The value returned for this is the size hint value of the underlying `slice::Iter`. This provides the most accurate size hint without needing to add additional fields for keeping track of the iterator's state.
I have been working on a project where it would be nice to pre-allocate collections based on the number of symbols inside an archive's symbol map. The default `.size_hint()` implementation returns 0 and there is no API in this library that will get this value.
=> Add `.size_hint()` implementation for `ArchiveSymbolIterator`

src/common.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/write/elf/object.rs, tests/round_trip/mod.rs
I'm not sure how correct this is but this seems to be enough to allow SuperH architecture ELFs to be opened.
=> Basic SuperH support

src/read/macho/symbol.rs
Closes #763 
I couldn't see any test cases this would hit, but a few examples of running this locally using the `objectmap` example vs main:
<details>
<summary>Full diff output on a compiled binary</summary>
```
❯ diff example_output_master example_output_branch
625a626,654
> 10003a198 0 __ZN11simple_test12STATIC_FIELD17hfda18a2f9fdf63afE /Users/sam/work/tardis/target/debug-test/deps/simple_test-f8e0227e6576d889.ektm87y5osdb2a6wchg62ejrj.rcgu.o
> 10003dbe8 0 __ZN4core7unicode12unicode_data15grapheme_extend17SHORT_OFFSET_RUNS17h5878be1170f5f7dfE /Users/sam/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-c8c2fe5a80a1416e.rlib(core-c8c2fe5a80a1416e.core.b495b0e88a16f434-cgu.0.rcgu.o)
> 10003dc70 0 …
```
=> Add support for parsing N_STSYM from the Mach-O symbol table

crates/examples/testfiles/wasm/base.o.objdump, src/read/wasm.rs
Partial support for #471 (The linking section contains other information that might also be useful but isn't supported yet.)
=> read/wasm: support symbol table in linking section

Cargo.lock, Cargo.toml
Since [1], this will come automatically from `rustc-std-workspace-core` and the crates.io dependency should no longer be specified.
[1]: https://github.com/rust-lang/rust/pull/141993
=> Remove `compiler-builtins` from `rustc-dep-of-std` dependencies

crates/examples/src/readobj/pe.rs, src/pe.rs, src/read/coff/file.rs, src/read/mod.rs
Used in Xbox 360 COFF. Technically it should return `Architecture::PowerPc64`, but it's unclear how to determine this from the COFF itself, so it returns `Architecture::PowerPc` for now. Define name and comment from https://github.com/microsoft/microsoft-pdb/blob/805655a28bd8198004be2ac27e6e0290121a5e89/cvdump/cvdump.cpp#L21.
Also adds PPC COFF magic(s) to `File::parse`.
=> Support big-endian PowerPC COFF

src/common.rs, src/read/elf/file.rs, src/read/elf/relocation.rs, src/write/elf/object.rs, tests/round_trip/mod.rs
[Dec Alpha](https://en.wikipedia.org/wiki/DEC_Alpha) is a 64 bit RISC architecture. 
Currently, I am working on adding support for this architecture to the upstream Rust compiler.
This PR contains some bare-bones support for this architecture. The code is complete enough to open some simple GCC-compiled executables, although I am not sure how to test a PR like this further.
=> Bare bones support for DEC Alpha

src/write/coff/object.rs
For PPC COFFs:
- relocation addends will now always evaluate to 0
- the appropriate file header will now be handled - even checks for endianness
- when adding symbols, if the symbol kind is a Label and the section is Undefined, we have an external symbol
=> Add additional logic to support writing PPC COFFs

crates/examples/src/readobj/elf.rs
This is valid when none of the relocations use symbols.
=> readobj: handle relocation sections with link 0

src/write/coff/object.rs
This matches LLVM, and works with the MSVC link.exe.
Closes #802
=> write/coff: use IMAGE_WEAK_EXTERN_SEARCH_ALIAS for weak externs
