gimli-rs/object

- Cargo.toml
- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/object_trait.rs
Care to rubber stamp this, @philipc?
See each commit for details.
> Random stuff

- Cargo.toml
- src/lib.rs
Does that ^
There will likely be another breaking change with segment too; sorry :/ I shouldn't have embedded the data objects inside the unified structs; maybe i'll keep it, it depends on how hard it makes writing mach-o object files for faerie
> Update to goblin 0.0.11

- .travis.yml
- Cargo.toml
Also switch to cargo-tarpaulin and add myself as an author.
> Bump to version 0.5.0

- src/lib.rs
> Deny missing debug implementations

- Cargo.toml
- examples/nm.rs
- examples/objdump.rs
`memmap` 0.6.0 introduces major API changes in anticipation of a 1.0
release. See https://github.com/danburkert/memmap-rs/releases/tag/0.6.0
for more information. CC danburkert/memmap-rs#33.
> Update to memmap 0.6

- examples/nm.rs
- examples/objdump.rs
- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/traits.rs
Fixes #23 
Also a few smaller additions that I needed for testing this in ddbug.
> Add Object trait back in

- examples/nm.rs
- examples/objdump.rs
- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/traits.rs
> Miscellaneous cleanup

- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/pe.rs
- src/traits.rs
> Add PE support

- src/lib.rs
Also lets us use this in more places.
> Avoid virtual calls

- Cargo.toml
> Update description and keywords

- .travis.yml
- Cargo.toml
- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/pe.rs
> Add no_std support

- src/elf.rs
> Don't decompress in ElfFile::has_debug_symbols()

- Cargo.toml
- src/pe.rs
Fixes: https://github.com/gimli-rs/object/issues/62
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> deps: update goblin to 0.0.17

- Cargo.toml
- src/macho.rs
This updates to 0.7 along with 1 major change which was made in the uuid release.
> Update uuid to 0.7

- src/elf.rs
- src/macho.rs
This fixes possible infinite loops when the data is corrupt.
> Fix handling of iterator errors

- examples/nm.rs
- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/pe.rs
- src/wasm.rs
I think the never taken loops were from when I was incorrectly ignoring errors.
Fixes #87
> Fix clippy warnings

- Cargo.toml
- examples/nm.rs
- examples/objdump.rs
- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/pe.rs
- src/traits.rs
- src/wasm.rs
By running `cargo fix --edition --edition-idioms`.
> Update to Rust 2018 edition

- src/elf.rs
- src/lib.rs
- src/macho.rs
> Add MIPS variant to Machine type

- src/wasm.rs
> Fix WasmSection::data

- examples/nm.rs
- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/pe.rs
- src/traits.rs
- src/wasm.rs
Add functions to correlate symbols with sections, and to get the data for a symbol.
> Symbol improvements

- Cargo.toml
- examples/nm.rs
- src/read/any.rs
- src/read/coff.rs
- src/read/mod.rs
COFF relocations will be in a future PR.
> Add COFF support

- Cargo.toml
- examples/nm.rs
- src/read/any.rs
- src/read/macho.rs
- src/read/mod.rs
> Improve Mach-O symbol and section kinds

- examples/objcopy.rs
- src/read/macho.rs
- src/write/macho.rs
- src/write/mod.rs
- tests/round_trip.rs
See individual commits.
Based on work by @jedisct1 in https://github.com/fastly/lucet/pull/271#issuecomment-528008121.
> Fixes for Mach-O writing

- src/write/mod.rs
> write: add Object::symbol_section_offset

- Cargo.toml
> Fix minor issues and bump version to 0.14.1

- Cargo.toml
ref https://github.com/CraneStation/cranelift/pull/1197
> build: update target-lexicon to 0.9, scroll to 0.10, and goblin to 0.1

- src/write/mod.rs
This is useful for supporting subsections.
> write: add Object::set_symbol_data

- src/write/coff.rs
Closes https://github.com/gimli-rs/object/issues/156
> Add amd64 support for relocation kind SectionIndex

- Cargo.toml
- README.md
- src/lib.rs
> Bump version to 0.17.0

- src/write/elf.rs
See https://github.com/bytecodealliance/cranelift/issues/1354 for context.
> Put read-only relocations in .data.rel.ro

- .travis.yml
- Cargo.toml
- src/endian.rs
- src/lib.rs
- src/pod.rs
- src/read/coff.rs
- src/read/elf.rs
- src/read/macho.rs
- src/read/mod.rs
- src/read/pe.rs
- src/read/wasm.rs
> Remove use of `feature(alloc)`

- src/read/elf.rs
Relocations for sections must use the SHT_SYMTAB symbol table, and must have a section index (not 0).
Fixes #195 (fixes the bug, but doesn't add an API for dynamic relocations).
> read/elf: fix handling of relocations for sections

- src/write/elf.rs
See https://github.com/bjorn3/rustc_codegen_cranelift/issues/921 for more context.
> write/elf: mark .data.rel.ro as SHF_WRITE

- src/read/coff/symbol.rs
- src/write/coff.rs
- tests/round_trip/common.rs
> coff: undefined symbols use IMAGE_SYM_CLASS_EXTERNAL

- src/elf.rs
- src/macho.rs
> Fix "unnecessary parentheses" warning

- examples/nm.rs
- src/common.rs
- src/read/elf/note.rs
- src/read/elf/section.rs
- src/write/coff.rs
- src/write/elf.rs
- src/write/macho.rs
- tests/round_trip/elf.rs
I'll add a test before merging.
> Fix ELF note alignment handling

- Cargo.toml
- examples/objcopy.rs
- examples/objdump.rs
- src/common.rs
- src/pe.rs
- src/read/any.rs
- src/read/coff/comdat.rs
- src/read/coff/file.rs
- src/read/coff/mod.rs
- src/read/coff/section.rs
- src/read/coff/symbol.rs
- src/read/elf/comdat.rs
- src/read/elf/file.rs
- src/read/elf/mod.rs
- src/read/elf/section.rs
- src/read/macho/file.rs
- src/read/pe/file.rs
- src/read/traits.rs
- src/read/wasm.rs
- src/write/coff.rs
- src/write/elf.rs
- src/write/mod.rs
- tests/round_trip/comdat.rs
- tests/round_trip/elf.rs
- tests/round_trip/mod.rs
Fixes #239 
I'll add tests before merging.
@carlokok Are you able to review this please?
> Implement COMDAT support

- Cargo.toml
- examples/ar.rs
- src/archive.rs
- src/lib.rs
- src/read/archive.rs
- src/read/mod.rs
Doesn't support reading the symbol table yet.
> read: add archive support

- Cargo.toml
- examples/objectmap.rs
- src/read/any.rs
- src/read/coff/symbol.rs
- src/read/macho/file.rs
- src/read/macho/symbol.rs
- src/read/mod.rs
- src/read/traits.rs
Maps from addresses to symbol names and object file names using Mach-O STAB entries.
> Add `ObjectMap`

- examples/ar.rs
- examples/objdump.rs
- src/read/macho/fat.rs
- src/read/macho/mod.rs
> read: implement Mach-O fat binary parsing

- Cargo.toml
- examples/objcopy.rs
- examples/objdump.rs
- src/read/any.rs
- src/read/coff/file.rs
- src/read/elf/file.rs
- src/read/elf/relocation.rs
- src/read/elf/section.rs
- src/read/macho/file.rs
- src/read/mod.rs
- src/read/pe/file.rs
- src/read/traits.rs
- src/read/util.rs
- src/read/wasm.rs
- tests/parse_self.rs
> read: parse dynamic relocations for ELF

- examples/nm.rs
- src/common.rs
- src/read/elf/section.rs
- src/write/coff.rs
- src/write/elf.rs
- src/write/macho.rs
Also fix handling of null symbol names in write/elf.
Fixes #251
> Add SectionKind::Elf 

- .github/workflows/rust.yml
- Cargo.toml
- examples/readobj.rs
- src/elf.rs
- src/pod.rs
- src/read/any.rs
- src/read/elf/comdat.rs
- src/read/elf/file.rs
- src/read/elf/note.rs
- src/read/elf/relocation.rs
- src/read/elf/section.rs
- src/read/elf/segment.rs
- src/read/elf/symbol.rs
- src/read/mod.rs
- tests/round_trip/elf.rs
Currently only prints ELF files.
> Add readobj example that uses the lower level read API

- examples/readobj.rs
- src/pod.rs
- src/read/coff/comdat.rs
- src/read/coff/file.rs
- src/read/coff/section.rs
- src/read/coff/symbol.rs
- src/read/mod.rs
- src/read/pe/file.rs
- src/read/pe/section.rs
There's still many PE data directories that we can't read yet though.
> readobj: COFF/PE support

- src/read/elf/file.rs
so managed to get the `d_val` now. may need to expose some more stuff.
Closes #275
> Add raw_header.

- src/write/macho.rs
- tests/round_trip/macho.rs
- tests/round_trip/mod.rs
> write/macho: fix segment size when first section needs alignment

- src/write/macho.rs
- src/write/mod.rs
> write/macho: don't panic for long section names

- examples/readobj.rs
> readobj: update mach-o definitions

- src/common.rs
- src/read/coff/file.rs
- src/read/elf/file.rs
- src/read/elf/relocation.rs
- src/read/pe/file.rs
- src/write/coff.rs
- src/write/elf.rs
- src/write/macho.rs
Update for consistency of supported machines and relocations for both read and write.
> elf: consistent architecture support

- src/common.rs
- src/read/mod.rs
- src/write/mod.rs
> Derive more traits for `FileKind` and other enums

- src/read/any.rs
- src/read/coff/comdat.rs
- src/read/coff/file.rs
- src/read/coff/section.rs
- src/read/coff/symbol.rs
- src/read/elf/comdat.rs
- src/read/elf/file.rs
- src/read/elf/section.rs
- src/read/elf/segment.rs
- src/read/elf/symbol.rs
- src/read/macho/file.rs
- src/read/macho/section.rs
- src/read/macho/segment.rs
- src/read/macho/symbol.rs
- src/read/pe/file.rs
- src/read/pe/section.rs
- src/read/traits.rs
- src/read/wasm.rs
> read: add `name_bytes` methods to traits

- Cargo.toml
- examples/elfcopy.rs
- examples/readobj.rs
- src/elf.rs
- src/lib.rs
- src/read/elf/symbol.rs
- src/write/elf/mod.rs
- src/write/elf/object.rs
- src/write/elf/writer.rs
- src/write/mod.rs
- src/write/string.rs
> Add `write::elf::Writer`

- crates/examples/src/readobj/pe.rs
- crates/examples/testfiles/pe/base.exe.readobj.0
- src/pe.rs
- src/read/pe/file.rs
- src/read/pe/rich.rs
Also style changes for rich header parsing.
> readobj/pe: print rich header

- crates/examples/Cargo.toml
- crates/examples/src/bin/pecopy.rs
- src/read/pe/data_directory.rs
- src/read/pe/file.rs
- src/read/pe/section.rs
- src/write/mod.rs
- src/write/pe.rs
- src/write/util.rs
> Add `write::pe::Writer`

- src/read/pe/section.rs
I felt reading the doc was not totally unambiguous for these functions
> [doc] Added minor precisions

- crates/examples/Cargo.toml
- crates/examples/src/bin/elftoefi.rs
- crates/examples/src/bin/pecopy.rs
- src/write/pe.rs
Includes some changes to `write::pe::Writer.
> examples: add elftoefi

- crates/examples/src/bin/elfcopy.rs
- src/read/elf/comdat.rs
- src/read/elf/symbol.rs
- src/read/macho/file.rs
- src/read/pe/file.rs
- src/read/wasm.rs
Also a bug fix for `read::elf::SymbolTable::shndx_section`.
> Fix warnings

- CHANGELOG.md
- src/elf.rs
- src/lib.rs
- src/macho.rs
- src/pe.rs
- src/read/elf/version.rs
- src/read/macho/dyld_cache.rs
- src/read/pe/rich.rs
- src/read/read_ref.rs
- src/write/coff.rs
- src/write/mod.rs
- src/write/string.rs
- src/xcoff.rs
This pull request fixes various typos in documentation / comments. No functional changes.
> Fix some typos

- Cargo.toml
- src/read/wasm.rs
> Update wasmparser dependency

- src/read/any.rs
This allows users to access format specific information.
Closes #563
> read: change File to an enum

- src/read/archive.rs
This is required for thin archives.
> read/archive: handle slashes in GNU member names

- crates/examples/src/readobj/mod.rs
- crates/examples/testfiles/archive/bsd.a.readobj
- crates/examples/testfiles/archive/gnu.a.readobj
- crates/examples/testfiles/archive/thin.a.readobj
- crates/examples/testfiles/coff/import_msvc.lib.readobj
- src/pod.rs
- src/read/archive.rs
> read/archive: add symbol iterator

- src/write/coff/writer.rs
- src/write/elf/writer.rs
- src/write/mod.rs
- src/write/pe.rs
> write: document that alignment must be a power of two

- src/write/elf/writer.rs
This was previously changed in #646
> write/elf: fix reserve_dynstr to match doc

- crates/examples/src/readobj/elf.rs
- crates/examples/testfiles/archive/bsd.a.readobj
- crates/examples/testfiles/archive/gnu.a.readobj
- crates/examples/testfiles/elf/base-aarch64.o.readobj
- crates/examples/testfiles/elf/base-aarch64.readobj
- crates/examples/testfiles/elf/base-mips64el.o.readobj
- crates/examples/testfiles/elf/base-mips64el.readobj
- crates/examples/testfiles/elf/base-strip.readobj
- crates/examples/testfiles/elf/base.o.readobj
- crates/examples/testfiles/elf/base.readobj
- crates/examples/testfiles/elf/nostd-mipsel.o.readobj
- crates/examples/testfiles/elf/nostd-mipsel.readobj
- crates/rewrite/testfiles/elf/base.noop
- src/read/elf/section.rs
> readobj/elf: delete duplicated field

- src/read/elf/relocation.rs
Same as https://github.com/gimli-rs/object/pull/725.
> Reformat code #2

- src/read/coff/relocation.rs
- src/read/macho/relocation.rs
- src/write/coff/object.rs
- src/write/elf/object.rs
- src/write/macho.rs
This matches changes previously done for ELF.
> Reformat relocation parsing

- src/common.rs
- src/read/elf/file.rs
- src/write/elf/object.rs
- tests/round_trip/mod.rs
LoongArch psABI Sepcs: https://github.com/loongson/la-abi-specs
> Add LoongArch32 ELF basic support

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/examples/Cargo.toml
- crates/examples/src/lib.rs
- crates/rewrite/Cargo.toml
- src/lib.rs
> Release 0.37.2

- crates/examples/src/readobj/elf.rs
- src/elf.rs
Add constants for the newly introduced SFrame.
> Add constants for GNU SFrame
